name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          # - x86_64-apple-darwin

    steps:
    - uses: actions/checkout@v4

    - name: Build with cross
      run: cross build --release --target ${{ matrix.target }}

    # - name: Install MinGW for Windows target
    #   if: matrix.target == 'x86_64-pc-windows-gnu'
    #   run: sudo apt-get update && sudo apt-get install -y mingw-w64

    - name: Install Rust target
      run: rustup target add ${{ matrix.target }}
    - name: Build for ${{ matrix.target }}
      run: cargo build --verbose --release --target ${{ matrix.target }}

    - name: Run tests (native only)
      if: matrix.target == 'x86_64-unknown-linux-gnu'
      run: cargo test --verbose

    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/kubectl-log-index
