name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install cross
      run: cargo install cross

    - name: Install Rust target
      run: rustup target add ${{ matrix.target }}

    - name: Build with cross
      run: cross build --release --target ${{ matrix.target }}

    # - name: Run tests (native only)
    #   if: matrix.target == 'x86_64-unknown-linux-gnu'
    #   run: cargo test --verbose
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/kubectl-log-index*

